# When changing the resolver, also update shell.nix accordingly!
resolver: lts-15.5
packages:
- .
extra-deps:
- git: https://github.com/nh2/linux-ptrace
  commit: 8969355c2e1ce095ef58acc5f2c5f8a4ea3f1645
- git: https://github.com/nh2/posix-waitpid.git
  commit: d2d7e06d85965dd022705d3d4e8348940afabb5f

allow-newer: true

nix:
  shell-file: shell.nix
